# フロントエンド（React）コンテナの開発用Docker設定

# ベースイメージとしてNode.jsを使用
FROM node:current-alpine3.22

# 作業ディレクトリを設定
WORKDIR /app

# package.jsonとpackage-lock.jsonをコピー
# npm installのキャッシュを効かせるため先にコピー
COPY package*.json ./

# 依存関係をインストール
RUN npm install

# アプリケーションのソースコードをコピー
COPY . .

# アプリケーションの起動コマンド
CMD ["npm", "run", "dev"]
