services:
  # Reactフロントエンドテストサービス
  frontend-test:
    container_name: react_frontend_test
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile.dev
    volumes:
      # ホストのコードをコンテナにマウント（開発用）
      - ./frontend:/app
    command: npm run test

  # FastAPIバックエンドテストサービス
  backend-test:
    container_name: fastapi_backend_test
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile.dev
    volumes:
      # ホストのコードをコンテナにマウント
      - ./backend:/app
    command: pytest
